// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c6704c57-4983-4a84-b31c-b77dce5d848d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMotorCommandChange();
void onResetFaultCommandChange();

String faultReasonCloud;
String systemState;
float anomalyCloud;
float confidenceCloud;
float objectTempCloud;
int systemStateCode;
bool faultLatchedCloud;
bool motorCommand;
bool motorRunning;
bool resetFaultCommand;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(faultReasonCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(systemState, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(anomalyCloud, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(confidenceCloud, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(objectTempCloud, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(systemStateCode, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(faultLatchedCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motorCommand, READWRITE, ON_CHANGE, onMotorCommandChange);
  ArduinoCloud.addProperty(motorRunning, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(resetFaultCommand, READWRITE, ON_CHANGE, onResetFaultCommandChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
